dataloader:
  name: "DIV2K"
  root: "/root/data3/ptc/datas/DIV2K/DIV2K_train_HR"

  image_size: 768

  shuffle: true
  num_workers: 4
  drop_last: false
  pin_memory: true

  device: "cuda:0"

  # 下面这些会通过 **dataset_kwargs 传给数据集构造函数
  prompt_file: "samples/DAPE_DIV2K_train_HR.txt"
  extensions:
    - ".png"
